<html>
    <h1> Мusic
        </h1>
        
    <iframe width="300" height="200" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/363471011&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/helennpham" title="helennpham" target="_blank" style="color: #cccccc; text-decoration: none;">helennpham</a> · <a href="https://soundcloud.com/helennpham/sets/lofi-hip-hop" title="| Chill | Lofi | Hip Hop |" target="_blank" style="color: #cccccc; text-decoration: none;">| Chill | Lofi | Hip Hop |</a></div>

<iframe width="300" height="200" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1145988220&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/djlavrushkin" title="Lavrushkin" target="_blank" style="color: #cccccc; text-decoration: none;">Lavrushkin</a> · <a href="https://soundcloud.com/djlavrushkin/gayazov-brother-malinovaya" title="GAYAZOV$ BROTHER$ - Малиновая Лада (Lavrushkin &amp; Tomboo Remix)" target="_blank" style="color: #cccccc; text-decoration: none;">GAYAZOV$ BROTHER$ - Малиновая Лада (Lavrushkin &amp; Tomboo Remix)</a></div>

<iframe width="300" height="200" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/865175467&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/femlove17" title="fem.love" target="_blank" style="color: #cccccc; text-decoration: none;">fem.love</a> · <a href="https://soundcloud.com/femlove17/uqwc2dwwmptp" title="фотографирую закат" target="_blank" style="color: #cccccc; text-decoration: none;">фотографирую закат</a></div>

<iframe width="300" height="200" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1078178521&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/user-189918221" title="Jaroslav" target="_blank" style="color: #cccccc; text-decoration: none;">Jaroslav</a> · <a href="https://soundcloud.com/user-189918221/feat-yoshimura-prod" title="Йоши-ПОПЫТ💡  (feat. Yoshimura/Йошимура) [prod Капуста]" target="_blank" style="color: #cccccc; text-decoration: none;">Йоши-ПОПЫТ💡  (feat. Yoshimura/Йошимура) [prod Капуста]</a></div>

<iframe width="300" height="200" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/836849248&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/olezhka-koshil" title="olezhka.koshil" target="_blank" style="color: #cccccc; text-decoration: none;">olezhka.koshil</a> · <a href="https://soundcloud.com/olezhka-koshil/morgenshtern-cadilac" title="MORGENSHTERN &amp; Эллжей - Cadilac (Кадиллак Моргенштерн)" target="_blank" style="color: #cccccc; text-decoration: none;">MORGENSHTERN &amp; Эллжей - Cadilac (Кадиллак Моргенштерн)</a></div>

<iframe width="300" height="200" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/227653564&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/user-909490133" title="Serene" target="_blank" style="color: #cccccc; text-decoration: none;">Serene</a> · <a href="https://soundcloud.com/user-909490133/sets/jtdymaxcglb5" title="Summer Nights" target="_blank" style="color: #cccccc; text-decoration: none;">Summer Nights</a></div>
<footer> ЭТО МУЗЫКА

:3

</footer> 
</html>
